### ISSUE TITLE
Argument Mismatch Error

### ISSUE THREAD

**Issue by aashishadhh** [cloudfoundry/fluent-plugin-syslog_rfc5424#15]
I am trying to use the plugin however, i am constantly getting this error. Cannot determine the root cause. 

`2022-11-15 19:14:22 +0000 [warn]: #0 got unrecoverable error in primary and no secondary error_class=ArgumentError error="wrong number of arguments (given 4, expected 3)"
2022-11-15 19:14:22 +0000 [info]: #0 [in_tail_container_logs] following tail of /var/log/containers/tunnelfront-5cf48899cb-rcbgl_kube-system_tunnel-front-ef4e999d296244ab7df584c77338875f83bc5979459e018b64fad76a532607d7.log
  2022-11-15 19:14:22 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin_helper/socket.rb:41:in `socket_create'
  2022-11-15 19:14:22 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/3.1.0/gems/fluent-plugin-syslog_rfc5424-0.8.0/lib/fluent/plugin/out_syslog_rfc5424.rb:53:in `find_or_create_socket'
  2022-11-15 19:14:22 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/3.1.0/gems/fluent-plugin-syslog_rfc5424-0.8.0/lib/fluent/plugin/out_syslog_rfc5424.rb:27:in `write'
  2022-11-15 19:14:22 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin/output.rb:1180:in `try_flush'
  2022-11-15 19:14:22 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin/output.rb:1501:in `flush_thread_run'
  2022-11-15 19:14:22 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin/output.rb:501:in `block (2 levels) in start'
  2022-11-15 19:14:22 +0000 [warn]: #0 /fluentd/vendor/bundle/ruby/3.1.0/gems/fluentd-1.15.2/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'
2022-11-15 19:14:22 +0000 [warn]: #0 bad chunk is moved to /tmp/fluent/backup/worker0/object_c3c8/5ed8729db52089d7f07b0d5cb8315a8f.log
2022-11-15 19:14:22 +0000 [info]: #0 fluentd worker is now running worker=0
2022-11-15 19:14:21.514600743 +0000 fluent.info: {"pid":15,"ppid":6,"worker":0,"message":"starting fluentd worker pid=15 ppid=6 worker=0"}`

**Comment by pilosula** [comment]
May I ask if there has been any progress on this issue? I have encountered the same problem
